<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>2757bce2-fded-4877-828b-62775cf8209a</UserSecretsId>
		<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
		<DockerfileContext>..\..\..</DockerfileContext>
		<DockerComposeProjectPath>..\..\..\docker-compose.dcproj</DockerComposeProjectPath>
	</PropertyGroup>

	<ItemGroup>
		<None Remove="Protos\discount.proto" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Grpc.AspNetCore" Version="2.83.0" />
		<PackageReference Include="Grpc.AspNetCore.Server.Reflection" Version="2.83.0" />
		<PackageReference Include="Mapster" Version="10.0.12" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.31" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.31">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.22.1" />
	</ItemGroup>

	<ItemGroup>
		<Protobuf Include="Protos\discount.proto" GrpcServices="Server" />
	</ItemGroup>

</Project>
